
```{r server_init_parameters, context="server"}
source("pop_plots.R")

population_size <<- 784

#viz parameters
point_size <<- 4   #glyph size - person
shield_size <<- 6  #glyph size - circle

shape_guide <<- 22

person_color <<- "grey"
death_color <<- "black"
hosp_color <<- "#58a758" #green
covid_color <<- "#bd4242" #"red
shield_color <<- "black"



# #renderui option
#ival <- reactiveVal(0)
#
# observeEvent(input$vacc_per_a,{
#   ival(input$vacc_per_a)
# })
# observeEvent(input$vacc_per_b,{
#   ival(input$vacc_per_b)
# })
# observeEvent(input$vacc_per_c,{
#   ival(input$vacc_per_c)
# })
# 
# output$slider_a <- renderUI({
#   newval <- ival()
#   sliderInput("vacc_per_a", "Percentual vacinado da população:", min = 0, max = 100, value = newval)}
# )
# output$slider_b <- renderUI({
#   newval <- ival()
#   sliderInput("vacc_per_b", "Percentual vacinado da população:", min = 0, max = 100, value = newval)}
# )
# output$slider_c <- renderUI({
#   newval <- ival()
#   sliderInput("vacc_per_c", "Percentual vacinado da população:", min = 0, max = 100, value = newval)}
# )

# #slider synch - original option
# observeEvent(input$vacc_per_a,{
#   if(input$vacc_per_a !=input$vacc_per_b)
#     isolate(updateSliderInput(inputId = "vacc_per_b", value = input$vacc_per_a))
#   if(input$vacc_per_a !=input$vacc_per_c)
#     isolate(updateSliderInput(inputId = "vacc_per_c", value = input$vacc_per_a))
#   # if(input$vacc_per_a !=ival())
#   #   ival(input$vacc_per_a)
# }, priority = 1)
# 
# observeEvent(input$vacc_per_b,{
#   if(input$vacc_per_b !=input$vacc_per_a)
#     isolate(updateSliderInput(inputId = "vacc_per_a", value = input$vacc_per_b))
#   if(input$vacc_per_b !=input$vacc_per_c)
#     isolate(updateSliderInput(inputId = "vacc_per_c", value = input$vacc_per_b))
# }, priority = 2)
# 
# observeEvent(input$vacc_per_c,{
#   if(input$vacc_per_c !=input$vacc_per_a)
#     isolate(updateSliderInput(inputId = "vacc_per_a", value = input$vacc_per_c))
#   if(input$vacc_per_c !=input$vacc_per_b)
#     isolate(updateSliderInput(inputId = "vacc_per_b", value = input$vacc_per_c))
# }, priority = 3)


#each plot a slider option
# ival <- reactiveVal(0)
# 
# observeEvent(input$vacc_per_01,{
#    ival(input$vacc_per_01)
#  })
# observeEvent(input$vacc_per_02,{
#    ival(input$vacc_per_02)
#  })
# observeEvent(input$vacc_per_03,{
#    ival(input$vacc_per_03)
#  })
# observeEvent(input$vacc_per_04,{
#    ival(input$vacc_per_04)
#  })
# observeEvent(input$vacc_per_05,{
#    ival(input$vacc_per_05)
#  })
# observeEvent(input$vacc_per_06,{
#    ival(input$vacc_per_06)
#  })
# observeEvent(input$vacc_per_07,{
#    ival(input$vacc_per_07)
#  })


population_by_vacc_per <- function(vacc_per) {
  return(get_population(population_size = population_size, 
                        infected_if_vacc_prob = 
                          get_infected_2_death_model()[["infected_if_vacc_prob"]]) %>%
           add_outcomes(vacc_per) %>%
           add_neat_x_y() %>%
           mutate(label = ifelse(coin_toss(size = population_size, 
                                           prob = c(0.5,0.5)),
                                 fontawesome('fa-male'),
                                 fontawesome('fa-female')))
         
  )
}

#generate population by vacc per
population_outcome_01 <- reactive({
  #vacc_per = ival() #input$vacc_per_a
  return(population_by_vacc_per(input$vacc_per_01))
})
population_outcome_02 <- reactive({return(population_by_vacc_per(input$vacc_per_02))})
population_outcome_03 <- reactive({return(population_by_vacc_per(input$vacc_per_03))})
population_outcome_04 <- reactive({return(population_by_vacc_per(input$vacc_per_04))})
population_outcome_05 <- reactive({return(population_by_vacc_per(input$vacc_per_05))})
population_outcome_06 <- reactive({return(population_by_vacc_per(input$vacc_per_06))})
population_outcome_07 <- reactive({return(population_by_vacc_per(input$vacc_per_07))})


#to display pop size as text
output$population_size_text <- renderText(population_size)

```

<!-- #PLOT VACC X N VACC -->
```{r plot_vacc_non_vacc, context="server"}
output$plot_vacc_non_vacc <- renderPlot({
  
  population_outcome_01() %>% 
    plot_vacc_non_vacc()
  
})
```

<!-- #PLOT VACC X N VACC X COVID -->
```{r plot_vacc_non_vacc_covid, context="server"}
output$plot_vacc_non_vacc_covid <- renderPlot({
  
  
  population_outcome_02() %>% 
    plot_vacc_non_vacc_covid()
  
  
})
```

<!-- #PLOT COVID BAR -->
```{r plot_covid_only, context="server"}
output$plot_covid_only <- renderPlot({
  #TO-DO:PERCENTUAIS DO TOTAL EM VALORES
  
  
  population_outcome_04() %>%
    plot_covid_only_waffle()
  
})
```

<!-- #PLOT PERC NA POP  -->
```{r plot_vacc_non_vacc_covid_sort, context="server"}
output$plot_vacc_non_vacc_covid_sort <- renderPlot({
  #TO-DO:GRAFICO de percentual em cada população
  #TO-DO:NEAT
  population_outcome() %>%
    plot_vacc_non_vacc_covid_sort()
})
```


<!-- #PLOT HOSP DEATH  -->
```{r plot_hosp_death, context="server"}
output$plot_hosp_death <- renderPlot({
  
  
  population_outcome_05() %>%
    plot_hosp_death()
})
```

<!-- #PLOT HOSP DEATH ONLY  -->
```{r plot_hosp_death_only, context="server"}
output$plot_hosp_death_only <- renderPlot({
  
  
  population_outcome_06() %>%
    plot_hosp_death_only()
})
```

<!-- #PLOT HOSP DEATH ONLY  -->
```{r plot_hosp_death_sort, context="server"}
output$plot_hosp_death_sort <- renderPlot({
  
  population_outcome() %>%
    plot_hosp_death_sort()
})
```
<!-- #SCORE PLOT  -->
```{r plot_score, context="server"}
output$plot_score <- renderPlot({
  
  
  population_outcome_03() %>%
    plot_score()
})
```
<!-- #SCORE PLOT  -->
```{r plot_score_final, context="server"}
output$plot_score_final <- renderPlot({
  
  
  population_outcome_07() %>%
    plot_score()
})
```
